@DevEvents.API_HostAddress = http://localhost:5088

### Create a new conference
POST {{DevEvents.API_HostAddress}}/conferences
Content-Type: application/json

{
    "title": "Tech Summit 2025",
    "description": "A conference for technology enthusiasts.",
    "startDate": "2025-06-10T09:00:00",
    "endDate": "2025-06-12T18:00:00"
}

### Get all conferences
GET {{DevEvents.API_HostAddress}}/conferences

### Get a specific conference by ID
GET {{DevEvents.API_HostAddress}}/conferences/1

### Update a conference
PUT {{DevEvents.API_HostAddress}}/conferences/1
Content-Type: application/json

{
    "title": "Updated Tech Summit 2025",
    "description": "A better and bigger conference for tech enthusiasts.",
    "startDate": "2025-06-10T09:00:00",
    "endDate": "2025-06-13T18:00:00"
}

### Delete a conference
DELETE {{DevEvents.API_HostAddress}}/conferences/1

### Add a registration to a conference
POST {{DevEvents.API_HostAddress}}/conferences/1/registrations
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@example.com"
}

### Add a speaker to a conference
POST {{DevEvents.API_HostAddress}}/conferences/1/speakers
Content-Type: application/json

{
    "name": "John Doe",
    "bio": ".NET Specialist",
    "website": "johndoe.com"
}

### HangfireEvents - Fire And Forget
GET {{DevEvents.API_HostAddress}}/fire-and-forget

### HangfireEvents - Fire And Forget - Continuation
GET {{DevEvents.API_HostAddress}}/fire-and-forget-continuation

### HangfireEvents - Fire And Forget - Delayed
GET {{DevEvents.API_HostAddress}}/fire-and-forget-delayed

### HangfireEvents - Recurring
GET {{DevEvents.API_HostAddress}}/recurring

### HangfireEvents - Job
GET {{DevEvents.API_HostAddress}}/cancel-job/recurring-job-70cdd9a0-c9c1-4f31-a6a1-5d79b728e2fe

